### ISSUE TITLE
User management 

### ISSUE THREAD

**Issue by kartik-gupta-ij** [parseablehq/console#111]
There are five entities in Parseable Access Control model - Action, Privilege, Resource, Role and User. Below section explains each of these entities in detail.

Admin, Editor, Writer and Reader. Below is the list of actions allowed for each Privilege.

Admin: All Actions.
Editor: Ingest, Query, CreateStream, ListStream, GetSchema, GetStats, GetRetention, PutRetention, PutAlert, GetAlert.
Writer: Ingest, Query, GetSchema, GetStats, GetRetention, PutAlert, GetAlert.
Reader: Query, GetSchema, GetStats, GetRetention, GetAlert.

**Comment by nitisht** [comment]
Fixed by #113
