### ISSUE TITLE
Feature Request: named saved filters in Logs page

### ISSUE THREAD

**Issue by Skryabind** [parseablehq/console#122]
It would be great to add ability to save filter set in Logs page. For example, I need to show only error logs with column "status" equals 500. It'd be more convenient to select saved filter in filter list.
And please add filter parameters to the query string - in this case I would add a link with predefined filter to bookmarks in browser.

**Comment by balaji-jr** [comment]
@Skryabind The saved filters feature was out in our latest release. Deriving the context from URL params will be covered in https://github.com/parseablehq/console/issues/146.
