### ISSUE TITLE
[Bug] Console doesn't show all data.

### ISSUE THREAD

**Issue by Skryabind** [parseablehq/console#134]
When I ask all logs from last 10 minutes, I see correct logs count but I don't see all this logs.
![2023-09-12_09-30-35](https://github.com/parseablehq/console/assets/4038319/30a73bdb-253f-4b29-ba7d-9c82be22d522)
In this screen I see that there is 26 log items in total, but only one log item in the list. The problem probably is in a query (highlited by an arrow in the screenshot) - startTime time equals 07:29:00, but correct time is 07:20:00.

**Comment by nitisht** [comment]
Thanks @Skryabind we'll take a look shortly

**Comment by Skryabind** [comment]
Hi @kartik-gupta-ij That time I hadn't this pagination, so I couldn't select another page. Unfortunately I selected another stack for holding logs so I cant check it now.

**Comment by nitisht** [comment]
Appreciate the response @Skryabind . Closing this issue for now, please feel free to reopen/update here if you get a chance to try and doesn't work as expected.
