### ISSUE TITLE
Title: Enhancements to Explore Page Search Functionality

### ISSUE THREAD

**Issue by aixart12** [parseablehq/console#196]
Issue Summary  
    - Search functionality on the explore page is activated only by pressing the Enter key.
    - No clear button available to reset the search input.
    - The reset button fails to clear both the search input and the applied filters.
    - Suggestion to implement debounce for API calls in the search input to improve performance and minimize unnecessary requests.
Expected Behavior:
    - A clear button should be available to reset the search input.
    - The reset button should clear both the search input and any applied filters.
    - Debounce should be implemented for search input to efficiently manage API calls.
    
 [Jam Link](https://jam.dev/c/0394d012-e3c3-4ad6-a27a-a349d018be19)

**Comment by nitisht** [comment]
This is very important - agreed @aixart12 . @balaji-jr is working on this already, we will have a better search / reset etc in the next release.

**Comment by balaji-jr** [comment]
Appreciate the observation @aixart12. 

1. API calls are not made for the search; instead, it searches locally using the loaded data. The search is triggered only when the user presses enter, eliminating the need for debounce. 
2. By looking at the linked jam, the button you are clicking does not represent a reset action; it serves as a refresh button. Its purpose is not to clear filters but to fetch logs for a specific time interval, especially crucial when 'Last n minutes' is selected. 
3. We are currently overhauling the filters to provide the capability to remove or reset specific filters.

@nitisht Stating the above, we can close this issue.
