### ISSUE TITLE
Issues with Table Functionality and Tooltip Display

### ISSUE THREAD

**Issue by aixart12** [parseablehq/console#212]
###  Description
There are multiple issues observed with the current implementation of table functionality and tooltip display in our project. Below are the details of the issues and a suggestion for improving the tooltip functionality.

###  1. Filter by Value Scrolling Issue
-   **Description**: The 'Filter by Value' functionality in tables is not scrolling properly. When users attempt to scroll through the list of values, the data vanishes if scrolled too much.
-    **Expected Behavior**: The data should remain visible and scroll smoothly, allowing users to select their desired filter values without any interruption.
-    **Steps to Reproduce**:
        -         Go to the table click on Datetime 
        -         Attempt to scroll through the list in  'Filter by Value'
        -         Notice that the data disappears or behaves erratically after a certain point.

![Filter by Value vanishing ](https://github.com/parseablehq/console/assets/59130412/38974d36-38bf-4c3e-a1c2-196221ff828b)

### 2. Tooltip Border Visibility
-    **Description**: The tooltip displayed over table values lacks a distinct border, causing it to blend in with the table's background. This makes it difficult to read the tooltip's content.
-    **Expected Behavior**: Tooltips should have a clear border or shadow to distinguish them from the table background, enhancing readability.
-    **Suggestion**: Implement a subtle border or shadow around tooltips.
![Tooltip blending with background](https://github.com/parseablehq/console/assets/59130412/9607bc1e-2cce-4a5c-b9fa-9b7a367067c4)

### 3. Tooltip Length Condition
-    **Suggestion**: It is proposed to display tooltips only for table values that exceed a certain length (e.g., more than 20 characters). This will prevent tooltips from cluttering the UI unnecessarily and focus the user's attention on longer values that might be truncated.
-    **Rationale**: This approach will enhance the user experience by providing additional context only when necessary, keeping the interface clean and focused.
![Tooltip not requied](https://github.com/parseablehq/console/assets/59130412/4ebfd234-8395-414b-a233-19ca1d03910e)

**Comment by nitisht** [comment]
Thanks for reporting @aixart12 , we’ll take a look.
