### ISSUE TITLE
Fix using legacy role privilege name: 'ingester' with Parseable v1.0.0+

### ISSUE THREAD

**Issue by krumpira** [parseablehq/console#245]
Hi, since Parseable v1.0.0, the legacy "ingester" role is renamed to "ingestor".
Staring Parseable required fixing it in parseable.json, but when using **console** (Parseable Web UI) to create new role, it complains:
```
Json deserialize error: unknown variant `ingester`, expected one of `admin`, `editor`, `writer`, `ingestor`, `reader` at line 1 column 24
```
because it uses the old privilege name.

It would be useful again for creating roles if this was corrected.

**Comment by nitisht** [comment]
Thank you @krumpira - much appreciated.
