### ISSUE TITLE
Home screen - Loading & Error states

### ISSUE THREAD

**Issue by balaji-jr** [parseablehq/console#347]
<img width="1462" alt="Screenshot 2024-10-27 at 8 23 05 AM" src="https://github.com/user-attachments/assets/6394eff4-65a2-401f-9412-8170ab769eb3">

1. When there are no streams show the empty placeholder (Search for `EmptyStreamsView`. Rename it to NoStreamsView and use it )
2. Show ParseableAnimated Loader when fetching streams
3. Add a shadow to the bottom of the header (Should appear only on scroll) & Display the total number of streams as `All Streams (23)`
<img width="1190" alt="Screenshot 2024-10-27 at 8 29 25 AM" src="https://github.com/user-attachments/assets/37b13dc3-84ba-43d2-8cb5-7c92bbe5cd6f">

**Comment by praveen5959** [comment]
1. What should be shown in case of empty streams for `All Streams` text? (i.e. `All Streams (0)`)
2. In case the API that fetches the list of Streams fails then what should be shown? Currently there is no error state or anything is shown.

cc: @balaji-jr

**Comment by balaji-jr** [comment]
1. In case of no streams available, the toolbar should be hidden and the No streams view must have two btns (Create stream btn and Read docs btn).
2. The same icon is in the No streams view with a toast displaying the error message. 

@praveen5959
