### ISSUE TITLE
Add PropTypes to shared components

### ISSUE THREAD

**Issue by ameen4455** [parseablehq/console#37]

**Comment by Aksa12** [comment]
I would like to work on this issue. Can you pls explain what do you mean by shared components here?

**Comment by nitisht** [comment]
Sure @Aksa12 . We'll get back in a bit. Meanwhile feel free to join the community slack https://launchpass.com/parseable for faster discussion on this.

**Comment by ameen4455** [comment]
@Aksa12 the shared components could be found in src/components
