### ISSUE TITLE
Sort log records by time field in reverse order

### ISSUE THREAD

**Issue by aaronjheng** [parseablehq/console#49]
Right now, Parseable Console queries logs in the form of `select * from <stream> order by <time>`. Can we sort log records by time field in reverse order, like `select * from <stream> order by <time> desc`?

**Comment by Abdul-Hafeez-Galib** [comment]
Hi can I work on this issue.

**Comment by nitisht** [comment]
Thanks @Abdul-Hafeez-Galib we'll test and merge this soon
