### ISSUE TITLE
Allow columns ordering

### ISSUE THREAD

**Issue by logut** [parseablehq/console#59]
It would be nice to be able change the columns order and have something custom instead of alphabetically.

In my usecase I have logs from an webserver so I would like the columnes to be in that order : datetime, host, uri, qs, status, ua instead of datetime, host, qs, status, ua, uri.

Maybe the oerder could also be restored on refresh like in #58.

**Comment by nitisht** [comment]
Thanks @logut . We'll add this to the roadmap.
