### ISSUE TITLE
Volunteer to improving the UI

### ISSUE THREAD

**Issue by Ryiski** [parseablehq/console#60]
I pretty much love Parseable and can't wait to see it hit production ready, but the UI seems Meh. 

I also seem to notice preference issues as mentioned in this [issue](https://github.com/parseablehq/console/issues/52)

I would like to work on starting over using this stack,

- React
- Vite
- Typescript
- Mantine UI

**Comment by nitisht** [comment]
Thank you for the kind offer @Ryiski . I do agree, console needs work. We've large plans for the console and can use the help.

Do you mind joining us on Community Slack (https://launchpass.com/parseable) for quick chat.

**Comment by nitisht** [comment]
Thank you for all the hard work on this one @Ryiski . We really appreciate your contributions. It is now being merged into the main branch in #71
